"""LLM-generated 'insurance fraud news' briefing for the dashboard news panel.

The items are generated by the app's Claude endpoint on first request and cached
in-process (there is no external news API / internet egress in the app runtime).
They are illustrative, professional demo content — not real, dated articles.
"""
from __future__ import annotations

import json
import re

from server.db import llm

# Simple process-wide cache so we don't call the LLM on every page load.
_CACHE: dict | None = None

_SYSTEM = (
    "You are a fraud-intelligence editor for an insurance analytics platform. "
    "Produce concise, realistic, professional news-style briefing items about fraud in the "
    "insurance sector (claims fraud, application fraud, organised rings, digital/identity fraud, "
    "regulation, detection technology, notable enforcement actions). "
    "Write in clear British English suitable for a claims-intelligence audience. "
    "These are illustrative briefing items for a demo dashboard, NOT real press articles: do NOT "
    "invent specific company names, real people, exact monetary figures presented as fact, or "
    "precise dates. Keep it thematic and plausible. Return STRICT JSON only."
)

_USER = (
    "Generate 6 insurance-fraud briefing items. Return a JSON object with a single key "
    '"items" whose value is an array of 6 objects, each with exactly these fields:\n'
    '  "category": one of "Claims Fraud", "Digital & Identity", "Organised Rings", '
    '"Regulation", "Detection Tech", "Market Trend"\n'
    '  "headline": a punchy 6-12 word headline (string)\n'
    '  "summary": 1-2 sentences (max ~40 words) explaining the item and why it matters (string)\n'
    '  "impact": one of "High", "Medium", "Low" — relevance to fraud teams\n'
    "Vary the categories across the 6 items. Return ONLY the JSON object, no prose, no code fences."
)

# Fallback content if the LLM call fails (e.g. serving endpoint unavailable), so the
# panel never renders empty or errors the page.
_FALLBACK = {
    "items": [
        {"category": "Claims Fraud", "impact": "High",
         "headline": "Staged motor collisions rise as cost-of-living pressures build",
         "summary": "Insurers report more induced and staged accident claims, with organised elements "
                    "recruiting willing drivers. Early triage on report-lag and injury patterns is key."},
        {"category": "Digital & Identity", "impact": "High",
         "headline": "Synthetic identities fuel a wave of application fraud",
         "summary": "Fraudsters blend real and fabricated data to pass onboarding checks, then file "
                    "inflated claims. Device and behavioural signals help separate genuine customers."},
        {"category": "Organised Rings", "impact": "Medium",
         "headline": "Cross-region ghost-broking networks target commercial policies",
         "summary": "Networks sell fake or manipulated commercial cover, leaving businesses unknowingly "
                    "uninsured. Link analysis across policyholders surfaces shared attributes."},
        {"category": "Detection Tech", "impact": "Medium",
         "headline": "Graph analytics and ML move fraud teams from reactive to proactive",
         "summary": "Combining network graphs with risk scoring flags suspicious clusters before payout, "
                    "shortening investigation cycles and reducing leakage."},
        {"category": "Regulation", "impact": "Medium",
         "headline": "Regulators push tighter data-sharing to fight claims fraud",
         "summary": "Proposed frameworks encourage cross-industry intelligence sharing while balancing "
                    "privacy — raising the bar for governed, auditable analytics."},
        {"category": "Market Trend", "impact": "Low",
         "headline": "Fraud loss ratios climb, sharpening focus on early detection",
         "summary": "As flagged payouts grow, carriers invest in real-time scoring at first notice of loss "
                    "to protect margins and honest policyholders."},
    ]
}


def _coerce(raw: str) -> dict:
    """Parse the LLM output into {items:[...]} defensively."""
    txt = (raw or "").strip()
    # strip code fences if present
    txt = re.sub(r"^```(?:json)?\s*|\s*```$", "", txt, flags=re.IGNORECASE).strip()
    # grab the outermost JSON object
    m = re.search(r"\{.*\}", txt, flags=re.DOTALL)
    if m:
        txt = m.group(0)
    data = json.loads(txt)
    items = data.get("items") if isinstance(data, dict) else data
    if not isinstance(items, list) or not items:
        raise ValueError("no items")
    clean = []
    allowed_impact = {"High", "Medium", "Low"}
    for it in items[:8]:
        if not isinstance(it, dict):
            continue
        clean.append({
            "category": str(it.get("category") or "Market Trend")[:40],
            "headline": str(it.get("headline") or "").strip()[:160],
            "summary": str(it.get("summary") or "").strip()[:400],
            "impact": it.get("impact") if it.get("impact") in allowed_impact else "Medium",
        })
    clean = [c for c in clean if c["headline"]]
    if not clean:
        raise ValueError("no valid items")
    return {"items": clean}


def news(refresh: bool = False) -> dict:
    """Return the fraud-news briefing (LLM-generated, cached in-process)."""
    global _CACHE
    if _CACHE is not None and not refresh:
        return _CACHE
    try:
        raw = llm(_SYSTEM, _USER, temperature=0.6, max_tokens=1200)
        result = _coerce(raw)
        result["source"] = "ai"
    except Exception:
        result = dict(_FALLBACK)
        result["source"] = "fallback"
    _CACHE = result
    return result
